### ISSUE TITLE
Fallback if no tags are present on the repo

### ISSUE THREAD

**Issue by LucHeart** [oprypin/find-latest-tag#13]
We use this in our CI pipeline to determine weather to set a docker image tag to latest or not during build and push.

The problem is, when someone forks the repo it does not come with tags. That makes the build fail.
So optimally we would have some way to have it fail silently and handle that in the workflow.

**Comment by oprypin** [comment]
Maybe try a setup like this? 

```yaml
  - uses: oprypin/find-latest-tag@v1
    with:
      repository: octokit/rest.js
    continue-on-error: true
```
