### ISSUE TITLE
Advertised tag precedence not being followed

### ISSUE THREAD

**Issue by anagyzambo-kx** [oprypin/find-latest-tag#14]
A chronologically newer version took precedence over a higher SemVer:
![image](https://github.com/user-attachments/assets/2e6f47ae-d9e9-45de-b736-afe605ce1305)

While the cert-manager releases are (https://github.com/cert-manager/cert-manager/releases):
![image](https://github.com/user-attachments/assets/74e921c9-0f86-4298-b275-85929d06c8b6)

Action steps:
```yaml
runs:
  using: "composite"
  steps:
    - id: latest
      name: Get latest version
      uses: oprypin/find-latest-tag@v1
      with:
        repository: ${{ inputs.owner }}/${{ inputs.repo }}
        releases-only: ${{ inputs.releases-only }}
        regex: '^(.*\d+\.\d\.?\d*|\d+)$'
        prefix: ${{ inputs.prefix }}
    - name: Update to latest
      shell: bash
      run: |
        ${{ github.action_path }}/action.sh
      env:
        INPUTS_FILE: ${{ inputs.file }}
        INPUTS_ID: ${{ inputs.id }}
        INPUTS_STRIP: ${{ inputs.strip }}
        LATEST_TAG: ${{ steps.latest.outputs.tag }}
```
